### ISSUE TITLE
Deploy And Maintain Branded Linux Clients (Enterprise Only)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-branding#21]
Seems my previous contribution got lost with any of the docs migrations… Here's the only trace I was able to find:
https://github.com/owncloud/documentation/blob/9594137c5fadf348fe1a8701d45f6365ebbaec4c/admin_manual/enterprise_clients/deploy_branded_linux_clients.rst

@mmattel @EParzefall could you add it here?
https://doc.owncloud.com/branded_clients/next/branded_desktop_client/

**Comment by mmattel** [comment]
@michaelstingl

With regards to the branding repo, I can assure you that none of the open issues or open pull request have been deleted. If you look at the closed parts of issue/pr at https://github.com/owncloud-archive/branded_clients, everything is clean. All issue have been transferred to this repo before moving and non of the open PR got closed before moving.

With regards to [https://github.com/owncloud/documentation/](https://github.com/owncloud/documentation/blob/9594137c5fadf348fe1a8701d45f6365ebbaec4c/admin_manual/enterprise_clients/deploy_branded_linux_clients.rst), this repo was migrated _many years ago_ and as you see on the filename referenced, it was using markdown (.rst) and not antora (.adoc).

**My proposal to fix this is the following:**

1. Let us know the target location in branding where the content should be visible.
2. I will create a PR having the content referenced in the old documentation link 1:1 at the location defined
3. You do a revision/update of all items that need a change
4. Standard procedure to finalize it

What we can't do is, to figure out of the two enterprise links what to document. This is beyond our knowledge and capability with the internals of branding. We are happy to support to bring defined content into docs.

**Comment by michaelstingl** [comment]
Yes, disappeared long time ago…

> * Let us know the target location in branding where the content should be visible.

I think it should be a new, 3rd page in https://doc.owncloud.com/branded_clients/next/branded_desktop_client/

> What we can't do is, to figure out of the two enterprise links what to document. This is beyond our knowledge and capability with the internals of branding. We are happy to support to bring defined content into docs.

It's only bringing the .rst to .adoc and integrate it nicely. All the content is on the old page.

**Comment by mmattel** [comment]
> new, 3rd page

Do you have a preferred name for this document?

**Comment by michaelstingl** [comment]
> Do you have a preferred name for this document?

I'd go for "Deploy And Update Branded Linux Desktop Clients". (`branded_linux_desktop_clients.html`)
